import type { constant } from '@/store/types';

export enum DROPZONE_ERROR {
  'DROPZONE_NO_ERROR' = 'DROPZONE_NO_ERROR',
  'DROPZONE_DATA_FETCH_ERROR' = 'DROPZONE_DATA_FETCH_ERROR',
  'DROPZONE_OUTLINE_FETCH_ERROR' = 'DROPZONE_OUTLINE_FETCH_ERROR',
}

export const DROPZONE_SET_SHOULD_SHOW_MAP_CONTROLS: constant =
  'DROPZONE_SET_SHOULD_SHOW_MAP_CONTROLS';
export const DROPZONE_SET_GEOGRAPHY_SELECTION: constant =
  'DROPZONE_SET_GEOGRAPHY_SELECTION';
export const DROPZONE_SET_VISIBILITIES: constant = 'DROPZONE_SET_VISIBILITIES';
export const DROPZONE_CONFIRM_SELECTION: constant =
  'DROPZONE_CONFIRM_SELECTION';
export const DROPZONE_SET_COORDINATES: constant = 'DROPZONE_SET_COORDINATES';
export const DROPZONE_SET_SELECTED_AREA: constant =
  'DROPZONE_SET_SELECTED_AREA';
export const DROPZONE_SET_EXCLUSIONS: constant = 'DROPZONE_SET_EXCLUSIONS';
export const DROPZONE_SET_ERROR: constant = 'DROPZONE_SET_ERROR';
export const DROPZONE_MAP_LOADING: constant = 'DROPZONE_MAP_LOADING';
export const DROPZONE_SET_OUTLINE: constant = 'DROPZONE_SET_OUTLINE';
export const DROPZONE_LOAD_OUTLINE: constant = 'DROPZONE_LOAD_OUTLINE';
