name: Coverage
on:
  pull_request:
    branches:
      - main
      - "updated-ui-design"
  

jobs:
  coverage:
    name: Coverage Reporter
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          # cache: 'pnpm'

      - run: pnpm install

      # - run: pnpm test:ci

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          test-script: pnpm test
          # coverage-file: report.json
          # base-coverage-file: report.json